import { Routes } from '@angular/router';
import { Ejemplo0 } from './components/ejemplo00/ejemplo0';
import { Ejemplo1 } from './components/ejemplo01/ejemplo1';
import { Ejemplo2 } from './components/ejemplo02/ejemplo2';
import { Ejemplo3 } from './components/ejemplo03/ejemplo3';
import { Ejemplo3b } from './components/ejemplo3b/ejemplo3b';
import { Ejemplo4b } from './components/ejemplo4b/ejemplo4b';
import { Ejemplo4 } from './components/ejemplo04/ejemplo4';
import { Ejemplo5 } from './components/ejemplo05/ejemplo5';
import { Ejemplo6 } from './components/ejemplo06/ejemplo6';
import { Ejemplo7 } from './components/ejemplo07/ejemplo7';
import { Ejercicio01 } from './components/ejercicio01/ejercicio01';
import { Ejemplo08 } from './components/ejemplo08/ejemplo08';
import { Ejemplo09 } from './components/ejemplo09/ejemplo09';
import { Ejemplo10 } from './components/ejemplo10/ejemplo10';
import { Ejemplo11 } from './components/ejemplo11/ejemplo11';
import { Ejemplo12Padre } from './components/ejemplo12-padre/ejemplo12-padre';
import { Ejemplo13Padre } from './components/ejemplo13-padre/ejemplo13-padre';
import { Ejemplo14 } from './components/ejemplo14/ejemplo14';
import { Ejemplo14b } from './components/ejemplo14b/ejemplo14b';
import { Ejemplo15 } from './components/ejemplo15/ejemplo15';
import { Ejemplo16 } from './components/ejemplo16/ejemplo16';
import { Ejemplo17 } from './components/ejemplo17/ejemplo17';
import { Ejercicio02 } from './components/ejercicio02/ejercicio02';
import { Ejemplo18 } from './components/ejemplo18/ejemplo18';
import { Ejemplo19 } from './components/ejemplo19/ejemplo19';
import { Ejemplo20a } from './components/ejemplo20a/ejemplo20a';
import { Ejemplo20b } from './components/ejemplo20b/ejemplo20b';
import { Ejemplo20c } from './components/ejemplo20c/ejemplo20c';
import { Ejemplo20d } from './components/ejemplo20d/ejemplo20d';
import { Ejemplo20e } from './components/ejemplo20e/ejemplo20e';
import { Ejemplo20f } from './components/ejemplo20f/ejemplo20f';

export const routes: Routes = [
  { path: 'ejemplo00', component: Ejemplo0 },
  { path: 'ejemplo01', component: Ejemplo1 },
  { path: 'ejemplo02', component: Ejemplo2 },
  { path: 'ejemplo03', component: Ejemplo3 },
  { path: 'ejemplo03b', component: Ejemplo3b },
  { path: 'ejemplo04', component: Ejemplo4 },
  { path: 'ejemplo04b', component: Ejemplo4b },
  { path: 'ejemplo05', component: Ejemplo5 },
  { path: 'ejemplo06', component: Ejemplo6 },
  { path: 'ejemplo07', component: Ejemplo7 },
  { path: 'ejemplo08', component: Ejemplo08 },
  { path: 'ejemplo09', component: Ejemplo09 },
  { path: 'ejemplo10', component: Ejemplo10 },
  { path: 'ejemplo11', component: Ejemplo11 },
  { path: 'ejemplo12', component: Ejemplo12Padre },
  { path: 'ejemplo13', component: Ejemplo13Padre },
  { path: 'ejemplo14', component: Ejemplo14 },
  { path: 'ejemplo14b', component: Ejemplo14b },
  { path: 'ejemplo15', component: Ejemplo15 },
  { path: 'ejemplo16', component: Ejemplo16 },
  { path: 'ejemplo17/:id', component: Ejemplo17 },
  { path: 'ejemplo18', component: Ejemplo18 },
  { path: 'ejemplo19', component: Ejemplo19 },
  { path: 'ejemplo20a', component: Ejemplo20a },
  { path: 'ejemplo20b', component: Ejemplo20b },
  { path: 'ejemplo20c', component: Ejemplo20c },
  { path: 'ejemplo20d', component: Ejemplo20d },  
  { path: 'ejemplo20e', component: Ejemplo20e },
  { path: 'ejemplo20f', component: Ejemplo20f },
  
  

  { path: 'ejercicio01', component: Ejercicio01 },
  { path: 'ejercicio02', component: Ejercicio02 },
];
